server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:~/h2-database-file
    username: sa
    driver-class-name: org.h2.Driver
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
    settings:
      web-allow-others: false
flyway:
  user: sa
#  password: 
  schemas: mart
  url: jdbc:h2:mem:DATABASE
  locations: filesystem:db/migration