CREATE TABLE PRODUCT_CATEGORY (ID BIGINT, 
	CAT_TYPE VARCHAR2,
	TAX DOUBLE,
	PRIMARY KEY(ID));
	
CREATE TABLE BILL (ID BIGINT, 
    TOTAL_COST DOUBLE, 
    TOTAL_TAX DOUBLE,
    STATUS VARCHAR2,
    CREATION_TIME TIMESTAMP,
    PRIMARY KEY(ID) );
    
CREATE TABLE PRODUCT (ID BIGINT, 
    NAME VARCHAR2, 
    COST DOUBLE,  
    PRODUCT_CATEGORY_ID BIGINT,
    PRIMARY KEY(ID),
    FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(ID));
    
CREATE TABLE ITEM (ID BIGINT,
	QUANTITY INTEGER, 
	TOTAL_COST DOUBLE,  
	TOTAL_TAX DOUBLE, 
	BILL_ID BIGINT,
	PRODUCT_ID BIGINT,
	PRIMARY KEY(ID),
	FOREIGN KEY(BILL_ID) REFERENCES BILL(ID),
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID));
	
CREATE SEQUENCE PRODUCT_CAT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE hibernate_sequence;

INSERT INTO PRODUCT_CATEGORY VALUES (NEXTVAL('PRODUCT_CAT_SEQ'),'A_TYPE', '0.1');
INSERT INTO PRODUCT_CATEGORY VALUES (NEXTVAL('PRODUCT_CAT_SEQ'),'B_TYPE', '0.2');
INSERT INTO PRODUCT_CATEGORY VALUES (NEXTVAL('PRODUCT_CAT_SEQ'),'C_TYPE', '0.0');

INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Tea', 100, 1);
INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Milk', 50, 1);
INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Perfume', 150, 2);
INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Shampoo', 200, 2);
INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Bottle', 250, 3);
INSERT INTO PRODUCT VALUES (NEXTVAL('PRODUCT_SEQ'),'Bucket', 300, 3);

